//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mtb_dbEntities : DbContext
    {
        public mtb_dbEntities()
            : base("name=mtb_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<booking> bookings { get; set; }
        public DbSet<movie> movies { get; set; }
        public DbSet<screen> screens { get; set; }
        public DbSet<seat> seats { get; set; }
        public DbSet<timeslot> timeslots { get; set; }
    }
}
