//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat
    {
        public seat()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public int seatID { get; set; }
        public int seatNumber { get; set; }
        public string Row { get; set; }
        public int screenID { get; set; }
        public string status { get; set; }
        public int price { get; set; }
    
        public virtual ICollection<booking> bookings { get; set; }
        public virtual screen screen { get; set; }
    }
}
