//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeslot
    {
        public timeslot()
        {
            this.movies = new HashSet<movie>();
        }
    
        public int timeslotID { get; set; }
        public string timeslotDisc { get; set; }
    
        public virtual ICollection<movie> movies { get; set; }
    }
}
